### ISSUE TITLE
Windows Spotlight don`t work with this

### ISSUE THREAD

**Issue by Kirillony** [HarshalKudale/NoMoreEdge#1]
If I click on Windows Spotlight caption, after logon I get cyclic window "wrong URL"
When I remove nomoreedge, i get MsEdge with opened URL:
https://www.bing.com/images/search?q=+%d0%bd%d0%b0%d1%86%d0%b8%d0%be%d0%bd%d0%b0%d0%bb%d1%8c%d0%bd%d1%8b%d0%b9+%d0%bf%d0%b0%d1%80%d0%ba+%d0%93%d1%91%d1%80%d0%b5%d0%bc%d0%b5&setlang=ru-ru&mkt=ru-ru&form=PLLSB1&first=1&tsc=ImageBasicHover

**Comment by HarshalKudale** [comment]
I will look into that. Thank for trying software.

**Comment by HarshalKudale** [comment]
Made some changed.  Now its working along with other simple URLs(that require no modification) .  Be sure to uninstall and install the app using same setup to get latest version.

**Comment by Kirillony** [comment]
Thanks a lot! Windows Spotlight work good now
