### ISSUE TITLE
Add option to install from commandline

### ISSUE THREAD

**Issue by Yannik** [HarshalKudale/NoMoreEdge#11]
Hi, 
I want to deploy NoMoreEdge automatically via GPO. 

Would it be possible to add some commandline-options so we can install it like this:

```NoMoreEdgeSetup.exe /install /search:"DuckDuckGo" /DDGbangs:"Yes" /NukeEdge:"Yes"```

(and uninstall with `NoMoreEdgeSetup.exe /uninstall`)

That would be great!

**Comment by HarshalKudale** [comment]
I will start working on it next week (College work is due). 
I dont really know what is GPO can you explain it a bit?

**Comment by Yannik** [comment]
It's a way to configure windows, see https://en.wikipedia.org/wiki/Group_Policy

**Comment by HarshalKudale** [comment]
So basically ability to install software using command line. Its really easy but will neee time because I will have to jam all the logic and paths from form into main function of setup.

Also GPO will let you download main exe file from GitHub right? because my software gets main exe files from corresponding github releases.

**Comment by Yannik** [comment]
I agree that the exe download is an issue.

I would suggest the following:
1. Integrate the `/install /search:"DuckDuckGo" /DDGbangs:"Yes" /NukeEdge:"Yes"` and `/uninstall` switches into `NoMoreEdge.exe`.
2. Call `NoMoreEdge.exe /search:"DuckDuckGo" /DDGbangs:"Yes" /NukeEdge:"Yes"` (or `/uninstall`) from `NoMoreEdgeSetup.exe` 

I think this is a really good solution.

**Comment by HarshalKudale** [comment]
> I agree that the exe download is an issue.

From next update it won't. I have embedded in setup file. Which also means setup is completely offline setup now.

**Comment by HarshalKudale** [comment]
I have managed to add command line options.I am still working on improving them and making them more usable for now this are as follows.

NoMoreEdgeSetup.exe -install google nukeedge-bang

-install can be replaced with -setup or -uninstall (setup is to update settings)

google can be replaced with othe engines that are already in list or with custom engine query.

nukeedge-bang can be replaced with nukeedge or bang seperately or default to keep them off.

for example. NoMoreEdgeSetup.exe -setup bing default

above command will only  work if NoMoreEdge is already install and will change engine to bing and setup default for nukeedge and bang.


I will push the update after some improvement and testing.

**Comment by HarshalKudale** [comment]
@Yannik New release is up with duckduckgo bugfix silent installer.
