### ISSUE TITLE
Not working on my Win 10 laptop with Ryzen 3

### ISSUE THREAD

**Issue by Apesbrain** [HarshalKudale/NoMoreEdge#13]
Have installed your great app on a few PCs, but not working on this particular one.  I only mention Ryzen because other laptops are Intel.  Can't think of anything I'm doing wrong as the install of your app is very straight-forward.  Any suggestions?  Thanks.

Does not work from search bar, nor from Win+R "microsoft-edge:https://google.com".

**Comment by HarshalKudale** [comment]
Pleasee provide following information.

Windows build version and specs info.
What output you are getting.
screenshot or video if possible.
Please check if your default browser for Microsoft-edge protocol is edge browser.

**Comment by Apesbrain** [comment]
It's the current build of Win 10: 19044.1415

With NoMoreEdge installed, typing in search box takes me to the pop-up to select Edge which I cancel.  On my other machines, doing this opens Chrome as set in your app.

URL:microsoft-edge was NOT set to any app.  Setting this to Edge allowed your app to work!

Thanks.
