### ISSUE TITLE
DuckDuckGo or customizable search engine?

### ISSUE THREAD

**Issue by shelbyKiraM** [HarshalKudale/NoMoreEdge#2]
Not that Google's evil or anything, but... No. I HAD a Firefox plugin I use already to redir Bing to DDG, it worked great with EdgeDeflector.

**Comment by HarshalKudale** [comment]
I am working on giving user option to choose search engine while installing . So till then please use google . I will add it very soon. BTW windows spotlight is working now be sure to uninstall and install NoMoreEdge using same setup.

**Comment by HarshalKudale** [comment]
Added this feature in new update. Please update the setup to get latest release

**Comment by shelbyKiraM** [comment]
Thanks a ton dude!! NO MÖAR EDGE!!!
