### ISSUE TITLE
Windows 10 searching from Start-S gives "wrong URL"?

### ISSUE THREAD

**Issue by shelbyKiraM-RIO** [HarshalKudale/NoMoreEdge#5]
Had to kill NoMoreEdge from task manager. Trying to use DDG. Clicking OK or closing the dialogue just reopens the same thing.

Changed to using Google, still getting the same error message. Is there any logging I can observe? Also for MICROSOFT-EDGE protocol in Default Apps, I have 2 Edge options, one has icon, other doesn't. But same error with both of those.

Any debugging log I can add?

Edit: oh, found this:
![image](https://user-images.githubusercontent.com/87328523/143920680-a5277754-8825-4977-99ae-5224e020df21.png)
WebView2? Uninstalled I still have 2 Microsoft Edge options in Default apps 🤷🏼‍♀️

**Comment by shelbyKiraM-RIO** [comment]
Oops, I made this on my work GH... @shelbyKiraM is the actual one hehe

**Comment by HarshalKudale** [comment]
I have added loop fix in new update. So if anyone has edge(any variant) as default browser then instead of giving wrong URL error it will open the URL in edge. I am uploading new release with fixes to GitHub in 1 hour. 

Also can you please provide steps to reproduce the error?

**Comment by HarshalKudale** [comment]
Can you check if it working in latest release or not? It will not loop even if default http and https app is edge.  As long as default app for Microsoft-edge;? protocol is edge app will work.

**Comment by shelbyKiraM-RIO** [comment]
It's working. Current default is set to the Edge with an icon.
![image](https://user-images.githubusercontent.com/87328523/144093899-ee226a47-6ec0-4615-807a-7a083cc2e6ff.png)
Just opening URLs from the start menu search is working now, too. Even when I switch to the Edge with no icon, still working. Even Win-R opens in Firefox on this PC. IDK what issue it had 🤷🏼‍♀️ 
![image](https://user-images.githubusercontent.com/87328523/144094559-13e84f12-c767-466b-83ff-41afd14ee399.png)

**Comment by HarshalKudale** [comment]
The issue was when calling edge with normal URLs ended up creating loop in IFEO. I fixed it in latest update. Hope it is working great now . Also DDG bangs are working.
