### ISSUE TITLE
[WIN11] Search results in Start Menu are still from Bing

### ISSUE THREAD

**Issue by sntxerror** [HarshalKudale/NoMoreEdge#6]
subj.

**Comment by HarshalKudale** [comment]
Can you please provide steps to reproduce. What version are you using?

**Comment by sounak-kun** [comment]
I second this. While search results once opened in the browser are from Google (and they open in my browser of choice), search results in the Start Menu are still from Bing.
![no_more_edge](https://user-images.githubusercontent.com/93094402/144481558-905d7428-67ed-4772-8cfa-ec70db13fa9c.png)
I am running Windows 11 Pro 21H2 - Build 22000.348

**Comment by HarshalKudale** [comment]
Sorry to say, but these but NoMoreEdge can not temper with those results. NoMoreEdge will only forward searches and links with Microsoft-edge:// protocol.all other links will be forwarded back to edge.

**Comment by sounak-kun** [comment]
Yes, expected as much. Still super useful tool to redirect search results from all the other windows settings. Thank you!

**Comment by HarshalKudale** [comment]
> Yes, expected as much. Still super useful tool to redirect search results from all the other windows settings. Thank you!

Thank you for understanding closing the issue.
